# Generated by Django 4.2.4 on 2023-08-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charginginfo', '0004_alter_charginginfo_end_dttm_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='charginginfo',
            table='ocpp_svr_charginginfo',
        ),
    ]
