# Generated by Django 4.1.5 on 2023-09-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpnumber', models.CharField(blank=True, max_length=64, verbose_name='충전기번호')),
                ('cpstatus', models.CharField(blank=True, max_length=64, verbose_name='충전기상태')),
                ('check_dttm', models.DateTimeField(blank=True, verbose_name='확인일시')),
                ('channel_name_1', models.CharField(blank=True, max_length=64, verbose_name='채널1이름')),
                ('channel_status_1', models.CharField(blank=True, max_length=64, verbose_name='채널1상태')),
                ('connection_id_1', models.CharField(blank=True, max_length=256, verbose_name='커넥션1아이디')),
                ('authorized_tag_1', models.CharField(blank=True, max_length=64, verbose_name='승인된1카드테그')),
                ('channel_name_2', models.CharField(blank=True, max_length=64, verbose_name='채널2이름')),
                ('channel_status_2', models.CharField(blank=True, max_length=64, verbose_name='채널2상태')),
                ('connection_id_2', models.CharField(blank=True, max_length=256, verbose_name='커넥션2아이디')),
                ('authorized_tag_2', models.CharField(blank=True, max_length=64, verbose_name='승인된2카드테그')),
            ],
            options={
                'verbose_name': '충전기채널',
                'verbose_name_plural': '충전기채널',
                'db_table': 'ocpp_svr_clients',
            },
        ),
    ]
