# Generated by Django 4.1.5 on 2023-09-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='check_dttm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='확인일시'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='connection_id_1',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='커넥션1아이디'),
        ),
    ]
