# Generated by Django 4.2.4 on 2023-08-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evcharger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpnumber', models.CharField(max_length=64, verbose_name='충전기번호')),
                ('cpsite', models.CharField(max_length=64, verbose_name='충전소이름')),
                ('partner_id', models.CharField(max_length=128, verbose_name='파트너아이디')),
                ('manager_id', models.CharField(max_length=128, verbose_name='관리자아이디')),
                ('public_use', models.BooleanField(default=True, verbose_name='공용')),
                ('cpstatus', models.CharField(max_length=64, verbose_name='충전기상태')),
                ('address', models.TextField(verbose_name='주소')),
                ('cpmodel', models.CharField(max_length=64, verbose_name='충전기모델')),
                ('cpmaker', models.CharField(max_length=64, verbose_name='충전기제조사')),
                ('fwversion', models.CharField(max_length=64, verbose_name='펌웨어버전')),
                ('register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('last_modified_dttm', models.DateTimeField(auto_now_add=True, verbose_name='최종정보변경일시')),
            ],
            options={
                'verbose_name': '충전기',
                'verbose_name_plural': '충전기',
                'db_table': 'ocpp_svr_evcharger',
            },
        ),
    ]
