# Generated by Django 4.1.5 on 2023-09-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msgapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpnumber', models.CharField(max_length=128, verbose_name='충전기번호')),
                ('carnumber', models.CharField(max_length=128, verbose_name='차량번호')),
                ('connector_id', models.IntegerField(verbose_name='커넥터아이디')),
            ],
            options={
                'verbose_name': '차량번호',
                'verbose_name_plural': '차량번호',
                'db_table': 'ocpp_svr_msgapi',
            },
        ),
    ]
