# Generated by Django 4.1.5 on 2023-12-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pvapi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpnumber', models.CharField(max_length=128, verbose_name='충전기번호')),
                ('password', models.CharField(max_length=128, verbose_name='차량번호')),
            ],
            options={
                'verbose_name': '충전기설정',
                'verbose_name_plural': '충전기설정',
                'db_table': 'ocpp_svr_pvapi',
            },
        ),
    ]
