# Generated by Django 4.1.5 on 2023-12-19 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('msgapi', '0002_pvapi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pvapi',
            old_name='cpnumber',
            new_name='client_id',
        ),
        migrations.RemoveField(
            model_name='pvapi',
            name='password',
        ),
        migrations.AddField(
            model_name='pvapi',
            name='origin',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='시리얼번호'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pvapi',
            name='pwd',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='패스워드'),
            preserve_default=False,
        ),
    ]
