# Generated by Django 4.1.5 on 2023-08-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='variables',
            table='ocpp_svr_variables',
        ),
    ]
