# Generated by Django 4.1.5 on 2023-08-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=64, verbose_name='아이디')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('name', models.CharField(max_length=64, verbose_name='이름')),
                ('email', models.EmailField(max_length=128, verbose_name='이메일')),
                ('phone', models.CharField(max_length=64, verbose_name='전화번호')),
                ('register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('last_use_dttm', models.DateTimeField(auto_now_add=True, verbose_name='최근사용일시')),
            ],
            options={
                'verbose_name': '관리자이름',
                'verbose_name_plural': '관리자이름',
                'db_table': 'ocpp_svr_admin',
            },
        ),
    ]
