# Generated by Django 4.1.5 on 2023-09-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='last_use_dttm',
            field=models.DateTimeField(verbose_name='최근사용일시'),
        ),
    ]
