# Generated by Django 4.1.5 on 2023-09-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_admin_last_use_dttm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='last_use_dttm',
            field=models.DateTimeField(auto_now_add=True, verbose_name='최근사용일시'),
        ),
    ]
