# Generated by Django 4.1.5 on 2023-08-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpconfig',
            options={'ordering': ['register_dttm'], 'verbose_name': '충전기설정', 'verbose_name_plural': '충전기설정'},
        ),
    ]
